language: generic

env:
  global:
   - secure: "M35pGRk9NMIdkr6qduZYdZ2l8fuwR+BpNLk/ZB184gxqsUWzPk2wUuZkVbzFeBbvC2Fp/2FFtYv6BweIws0tBjgKCcyyT2Az9kx2tnH2Q3lZ4NHEhXH/h027AHPZBGfYosgpMXfwVycfTQ4romlOtnLRDwxI/dwux1ASEY3F4pKbLfUQ2pVIHhPJlcPrVvpOR4b2ky3n3GSFdAF8QXfHkY6BOnLYXCLacSoEIsm0Gji0wQU3qf/pyqlOoJY/m0vBXkAqdUW/PspbP4FtklAscNSSWFYOezmwNH8o1xER4CduVFuk3fn4jXHPQ1jKzIn7RBociEpPGjxUFvgDVfcG8z2jbA3uP4iKgfvLBg4qRhaJenTwWzMnmfxYnP5IaRMpYk7EtSCjWhvZX3mau8i+JHRZCr2AdAHi0XXKYLyFsnCYjYd9O3FDsB/hAJGFdN9I0Ibq5XOT9qkORkxu7Us1l6qlJVWo+dWASuJkFEIBkfzs9/UCk4Qwl4W5O8wNFcthxpRQdDoGV/xqqjkv9PJb24vIPpKArpzngtpxNxN/PP6a+4qOix+EjlhmLKdkMeyKLoYK/587VbA/BOwrlRROir15jray9jV7NdzVCZkuueSpQtKGDqHjbso8f21F4aj8Jf7QeQq5MWqksIXanR80pDbDHCaBTN1QIaFjMwAG3Dg="

addons:
  sonarqube:
    token:
      secure: "xDviASS2LQpsozu47j+JPTMidO06mkrhnIBOW+SyPzlofJ/Bq1lFXJ+kUEfsFIPGIWe4iDCbJ3FFVVEx1rAWuAFR7IWwQUbGUMye+jqviN0XaSTe/tPcmyj0JoDvyQcs+PSL4vx98vTKsNUHHM1ZgFjGl5ax60Y7ytZmRcZltymsbPh6EFYJBmo92uptVzcG6W2sifU1Zv4o0hXFhgiJF60kqVSr02Ipd8asXG3vICVlVCymMM0CgZD8ZzDgNGZ0obL3DF8SEbtjzQXn3czZliqZsqWnW/YYCGi6DaGVAi78ahGAly1bTK/6p3STMs49odxrk0aSgCiOhsD28q+8vekjGLjIl5PV4chEUiKIfzDP5WjBz7b7idun63G0IBpLDfI7gxsvPRXbm0y/wV0LGweVm+4HBb2H47w/OW+mT6Itce3TWywf7MI+ebCr/bm9SX1SY7FyZS1vTA68A29GVfXHkZUhhgdT6WZbzPIi2Kwb9mBE3+FtxcCexKHISKdIFIl+zm7ebL9O+YxyW6rTAq6A7tEObHUpcIQeeelZ2qg5s5QFMkiOBLrG82RfuLv9zkQxu2j9Wg775w9kieW8jSuGhCDlErZy9Nfoyxf0e0P3Y9ZejleEDuLy4hiABxiMhngVD29v8bLCYjx10uc3oPGTl+/FkffH4rP0LXCBftI="

before_install:
 - sudo apt-get install yui-compressor
 
install:
 - chmod +x ./deploy.sh

script:
 - ls -alrt
 - ./deploy.sh

after_script:
 - sonar-scanner

notifications:
  email: false